import os
from conan.internal.cache.home_paths import HomePaths
from conan.internal.loader import load_python_file
from conan.internal.errors import ConanException

def tar_extract(cache_folder, src_path, destination_dir):
    compress_plugin = _load_compress_plugin(cache_folder)
    compress_plugin.tar_extract(src_path, destination_dir)

def tar_compress(cache_folder, files, name, dest_dir, compresslevel=None, ref=None):
    compress_plugin = _load_compress_plugin(cache_folder)
    return compress_plugin.tar_compress(files, name, dest_dir, compresslevel, ref)

def _load_compress_plugin(cache_folder):
    compression_plugin_path = HomePaths(cache_folder).compression_plugin_path
    if not os.path.exists(compression_plugin_path):
        # TODO
        raise ConanException("The 'compression.py' plugin file doesn't exist. If you want "
                             "to disable it, edit its contents instead of removing it")

    mod, _ = load_python_file(compression_plugin_path)
    if not hasattr(mod, "tar_extract") or not hasattr(mod, "tar_compress"):
        raise ConanException("The 'compression.py' plugin does not contain required `tar_extract` or `tar_compress` functions")
    return mod


_default_compression_plugin = """\
# This file was generated by Conan. Remove this comment if you edit this file or Conan
# will destroy your changes.

import os
import time
import tarfile
from conan.api.output import ConanOutput

def tar_compress(files, name, dest_dir, compresslevel=None, ref=None):
    t1 = time.time()
    # FIXME, better write to disk sequentially and not keep tgz contents in memory
    tgz_path = os.path.join(dest_dir, name)
    ConanOutput(scope=str(ref)).info(f"Compressing {name}")
    with set_dirty_context_manager(tgz_path), open(tgz_path, "wb") as tgz_handle:
        tgz = gzopen_without_timestamps(name, fileobj=tgz_handle, compresslevel=compresslevel)
        for filename, abs_path in sorted(files.items()):
            # recursive is False in case it is a symlink to a folder
            tgz.add(abs_path, filename, recursive=False)
        tgz.close()

    duration = time.time() - t1
    ConanOutput().debug(f"{name} compressed in {duration} time")
    return tgz_path


def tar_extract(src_path, destination_dir):
    with open(src_path, mode='rb') as file_handler:
        the_tar = tarfile.open(fileobj=file_handler)
        # NOTE: The errorlevel=2 has been removed because it was failing in Win10, it didn't allow to
        # "could not change modification time", with time=0
        # the_tar.errorlevel = 2  # raise exception if any error
        the_tar.extraction_filter = (lambda member, path: member)  # fully_trusted, avoid Py3.14 break
        the_tar.extractall(path=destination_dir)
        the_tar.close()
"""

def migrate_compression_plugin(cache_folder):
    from conan.internal.api.migrations import update_file

    profile_plugin_file = HomePaths(cache_folder).compression_plugin_path
    update_file(profile_plugin_file, _default_compression_plugin)

