from conans.model import Generator
from conans.client.generators.qmake import DepsCppQmake
from conans.paths import BUILD_INFO_QMAKE_SUBDIRS

generic_prf_template = """
message("Conan: Using autogenerated {name}.prf")
INCLUDEPATH *= {deps.include_paths}
LIBS *= {deps.lib_paths} {deps.libs}
DEFINES *= {deps.defines}
QMAKE_CXXFLAGS *= {deps.cppflags}
QMAKE_CFLAGS *= {deps.cflags}
QMAKE_LFLAGS *= {deps.exelinkflags}
QMAKE_LFLAGS *= {deps.sharedlinkflags}
"""

class QmakeSubDirsGenerator(Generator):

    @property
    def content(self):
        ret = {BUILD_INFO_QMAKE_SUBDIRS: "#include this file in your .qmake.conf\nQMAKEFEATURES *= $$PWD"}

        for dep_name, dep_cpp_info in self.deps_build_info.dependencies:
            dep_name = dep_name.replace("-", "_").replace(".", "_")
            deps = DepsCppQmake(dep_cpp_info)
            ret["{0}.prf".format(dep_name)] = generic_prf_template.format(name=dep_name, deps=deps )

        return ret

    @property
    def filename(self):
        pass