import platform
import textwrap

import pytest

from conan.test.utils.tools import TestClient

# Shared by every test below: generic glue that links whatever ZigDeps generated and runs it.
# Nothing here is package-specific, so a single build.zig/consumer shape covers all scenarios.
_BUILD_ZIG = textwrap.dedent("""
    const std = @import("std");
    const conan_setup = @import("conan_zig_deps/conan_setup.zig");

    pub fn build(b: *std.Build) void {
        const target = b.standardTargetOptions(.{});
        const optimize = b.standardOptimizeOption(.{});

        const mod = b.createModule(.{ .target = target, .optimize = optimize });
        mod.addCSourceFile(.{ .file = b.path("main.c"), .flags = &.{} });
        mod.link_libc = true;

        const exe = b.addExecutable(.{ .name = "app", .root_module = mod });
        conan_setup.linkDependencies(mod);
        b.installArtifact(exe);

        const run_cmd = b.addRunArtifact(exe);
        run_cmd.step.dependOn(b.getInstallStep());
        const run_step = b.step("run", "Run the app");
        run_step.dependOn(&run_cmd.step);
    }
    """)


def _app_conanfile(requires):
    # ``settings`` matters here beyond package_id: VirtualRunEnv reads settings.os to decide
    # whether to export (DY)LD_LIBRARY_PATH at all, so a consumer that declares no settings
    # gets an empty conanrun environment and its shared dependencies stay unfindable.
    return textwrap.dedent("""
        from conan import ConanFile

        class App(ConanFile):
            settings = "os", "compiler", "build_type", "arch"
            requires = "%s"
            generators = "ZigDeps"

            def build(self):
                # ZigDeps only wires dependencies up for the *build*; making shared libraries
                # loadable at *run* time is Conan's job, through the auto-generated conanrun
                # environment (PATH on Windows, (DY)LD_LIBRARY_PATH elsewhere). Same idiom as
                # test_cps.py and test_cmakeconfigdeps_new_cpp_linkage.py.
                self.run("zig build run", env="conanrun")
        """) % requires


def _main_c(function_name):
    return textwrap.dedent("""
        #include <stdio.h>
        extern int %s(void);
        int main(void) {
            printf("%s=%%d\\n", %s());
            return 0;
        }
        """) % (function_name, function_name, function_name)


def _build_zig_single_target(target_name):
    """ Like _BUILD_ZIG, but calls linkDependency() for one specific target directly instead
    of linkDependencies() - which would link every direct dependency wholesale """
    return textwrap.dedent("""
        const std = @import("std");
        const conan_setup = @import("conan_zig_deps/conan_setup.zig");

        pub fn build(b: *std.Build) void {
            const target = b.standardTargetOptions(.{});
            const optimize = b.standardOptimizeOption(.{});

            const mod = b.createModule(.{ .target = target, .optimize = optimize });
            mod.addCSourceFile(.{ .file = b.path("main.c"), .flags = &.{} });
            mod.link_libc = true;

            const exe = b.addExecutable(.{ .name = "app", .root_module = mod });
            conan_setup.linkDependency(mod, "%s");
            b.installArtifact(exe);

            const run_cmd = b.addRunArtifact(exe);
            run_cmd.step.dependOn(b.getInstallStep());
            const run_step = b.step("run", "Run the app");
            run_step.dependOn(&run_cmd.step);
        }
        """) % target_name


# Conan's Windows binaries are built with MSVC, but Zig defaults to the MinGW (gnu) ABI on
# Windows - and only ships libc for that ABI. Linking an MSVC-produced object in gnu mode
# fails on the /DEFAULTLIB:MSVCRT and /DEFAULTLIB:OLDNAMES directives it carries, which lld
# then looks for under MinGW names (libMSVCRT.a). Tests whose dependencies are built by
# CMake - i.e. by MSVC on Windows - therefore have to ask for the matching ABI. Tests that
# build their dependencies with `zig cc` do not: those are gnu on both sides already.
_BUILD_ZIG_MATCHING_CONAN_ABI = _BUILD_ZIG.replace(
    'const std = @import("std");',
    'const std = @import("std");\nconst builtin = @import("builtin");', 1
).replace(
    "    const target = b.standardTargetOptions(.{});",
    "    // Match the ABI of the Conan binaries: MSVC on Windows, native elsewhere.\n"
    "    var query: std.Target.Query = .{};\n"
    "    if (builtin.os.tag == .windows) query.abi = .msvc;\n"
    "    const target = b.standardTargetOptions(.{ .default_target = query });", 1)


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps():
    """ A real ``zig build`` links a Conan static-library dependency (with 2 components,
    one requiring the other) through the glue generated by ZigDeps, and runs successfully """
    c = TestClient()
    liba_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class LibA(ConanFile):
            name = "liba"
            version = "1.0"
            package_type = "static-library"
            exports_sources = "comp1.c", "comp1.h", "comp2.c", "comp2.h"

            def build(self):
                self.run("zig cc -c comp1.c -o comp1.o")
                self.run("zig cc -c comp2.c -o comp2.o")
                self.run("zig ar rcs libcomp1.a comp1.o")
                self.run("zig ar rcs libcomp2.a comp2.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.components["comp1"].libs = ["comp1"]
                self.cpp_info.components["comp1"].requires = ["comp2"]
                self.cpp_info.components["comp2"].libs = ["comp2"]
        """)
    comp1_h = 'int comp1_value(void);\n'
    comp1_c = textwrap.dedent("""
        extern int comp2_value(void);
        int comp1_value(void) { return comp2_value() + 1; }
        """)
    comp2_h = 'int comp2_value(void);\n'
    comp2_c = 'int comp2_value(void) { return 41; }\n'

    c.save({"liba/conanfile.py": liba_conanfile,
            "liba/comp1.h": comp1_h,
            "liba/comp1.c": comp1_c,
            "liba/comp2.h": comp2_h,
            "liba/comp2.c": comp2_c,
            "conanfile.py": _app_conanfile("liba/1.0"),
            "build.zig": _BUILD_ZIG,
            "main.c": _main_c("comp1_value")})
    c.run("create liba")
    c.run("build .")
    assert "comp1_value=42" in c.out


@pytest.mark.slow
@pytest.mark.tool("cmake")
@pytest.mark.tool("zig")
def test_zigdeps_cmake_deps():
    """ Same graph as test_zigdeps (2 static components, one requiring the other), but the
    dependency is built with CMake+the system compiler instead of ``zig cc`` - only the final
    consumer uses Zig, proving ZigDeps works on binaries it had no part in producing """
    c = TestClient()
    liba_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout

        class LibA(ConanFile):
            name = "liba"
            version = "1.0"
            package_type = "static-library"
            settings = "os", "compiler", "build_type", "arch"
            exports_sources = "CMakeLists.txt", "comp1.c", "comp1.h", "comp2.c", "comp2.h"
            generators = "CMakeToolchain"

            def layout(self):
                cmake_layout(self)

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.components["comp1"].libs = ["comp1"]
                self.cpp_info.components["comp1"].requires = ["comp2"]
                self.cpp_info.components["comp2"].libs = ["comp2"]
        """)
    liba_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(liba C)
        add_library(comp2 STATIC comp2.c)
        add_library(comp1 STATIC comp1.c)
        target_link_libraries(comp1 PUBLIC comp2)
        install(TARGETS comp1 comp2
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES comp1.h comp2.h DESTINATION include)
        """)
    comp1_h = 'int comp1_value(void);\n'
    comp1_c = textwrap.dedent("""
        extern int comp2_value(void);
        int comp1_value(void) { return comp2_value() + 1; }
        """)
    comp2_h = 'int comp2_value(void);\n'
    comp2_c = 'int comp2_value(void) { return 41; }\n'

    c.save({"liba/conanfile.py": liba_conanfile,
            "liba/CMakeLists.txt": liba_cmakelists,
            "liba/comp1.h": comp1_h,
            "liba/comp1.c": comp1_c,
            "liba/comp2.h": comp2_h,
            "liba/comp2.c": comp2_c,
            "conanfile.py": _app_conanfile("liba/1.0"),
            "build.zig": _BUILD_ZIG_MATCHING_CONAN_ABI,
            "main.c": _main_c("comp1_value")})
    c.run("create liba")
    c.run("build .")
    assert "comp1_value=42" in c.out


def _shared_ext():
    system = platform.system()
    if system == "Darwin":
        return ".dylib"
    if system == "Windows":
        return ".dll"
    return ".so"


def _shared_link_flags(libname):
    """ Platform-specific flags a shared library needs at link time: an ``@rpath`` install
    name on Darwin (what Conan packages normally carry, and what ``DYLD_LIBRARY_PATH`` from
    conanrun resolves by leaf name), a soname on Linux/ELF as the equivalent, and an explicit
    import library on Windows (LLD's MinGW-compatible COFF linker, unlike a plain ELF/Mach-O
    link, doesn't produce one unless asked - matching the .a naming Conan's own
    auto-deduction regex expects) """
    system = platform.system()
    if system == "Darwin":
        return "-install_name @rpath/lib%s%s" % (libname, _shared_ext())
    if system == "Windows":
        return "-Wl,--out-implib,lib%s.a" % libname
    return "-Wl,-soname,lib%s%s" % (libname, _shared_ext())


def _export_header(libname, function_name):
    """ A portable dllexport/dllimport header for a shared library built directly with
    ``zig cc``: on Windows, symbols aren't exported by default (unlike CMake's
    WINDOWS_EXPORT_ALL_SYMBOLS), so the .c file defining ``function_name`` must be compiled
    with ``-D<libname>_EXPORTS`` (matching CMake's own auto-defined macro name) for this to
    resolve to dllexport there; any other translation unit merely consuming the header
    (without that define) correctly sees dllimport instead """
    return textwrap.dedent("""
        #if defined(_WIN32) && defined(%s_EXPORTS)
        #define %s_API __declspec(dllexport)
        #elif defined(_WIN32)
        #define %s_API __declspec(dllimport)
        #else
        #define %s_API
        #endif
        %s_API int %s(void);
        """) % (libname, libname.upper(), libname.upper(), libname.upper(),
               libname.upper(), function_name)


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_shared_chain():
    """ A chain of two shared libraries (shareda -> sharedb): both get linked, and both are
    found at runtime through conanrun rather than through anything the generator emits """
    c = TestClient()
    ext = _shared_ext()
    sharedb_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class SharedB(ConanFile):
            name = "sharedb"
            version = "1.0"
            package_type = "shared-library"
            exports_sources = "sharedb.c", "sharedb.h"

            def build(self):
                self.run("zig cc -shared -fPIC -Dsharedb_EXPORTS %s -o libsharedb%s sharedb.c")

            def package(self):
                # Split by pattern, not by platform: the runtime-loadable file (.so/.dylib/
                # .dll) goes to bindirs on Windows (where Conan's own auto-deduction looks
                # for it) and libdirs everywhere else; any import library (.a, Windows-only
                # here) always goes to libdirs. Harmless no-ops for the patterns that don't
                # apply to the current platform.
                copy(self, "*.dll", self.build_folder, os.path.join(self.package_folder, "bin"))
                copy(self, "*.so*", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.dylib", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["sharedb"]
        """) % (_shared_link_flags("sharedb"), ext)
    shareda_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class SharedA(ConanFile):
            name = "shareda"
            version = "1.0"
            package_type = "shared-library"
            requires = "sharedb/1.0"
            exports_sources = "shareda.c", "shareda.h"

            def build(self):
                dep = self.dependencies["sharedb"].cpp_info
                self.run('zig cc -c -Dshareda_EXPORTS shareda.c -I"'
                         + dep.includedirs[0] + '" -o shareda.o')
                self.run('zig cc -shared -fPIC %s -o libshareda%s shareda.o -L"'
                         + dep.libdirs[0] + '" -lsharedb')

            def package(self):
                copy(self, "*.dll", self.build_folder, os.path.join(self.package_folder, "bin"))
                copy(self, "*.so*", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.dylib", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["shareda"]
        """) % (_shared_link_flags("shareda"), ext)

    sharedb_h = _export_header("sharedb", "shared_b_value")
    sharedb_c = textwrap.dedent("""
        #include "sharedb.h"
        int shared_b_value(void) { return 10; }
        """)
    shareda_h = _export_header("shareda", "shared_a_value")
    shareda_c = textwrap.dedent("""
        #include "shareda.h"
        #include "sharedb.h"
        int shared_a_value(void) { return shared_b_value() + 1; }
        """)

    c.save({"sharedb/conanfile.py": sharedb_conanfile,
            "sharedb/sharedb.h": sharedb_h,
            "sharedb/sharedb.c": sharedb_c,
            "shareda/conanfile.py": shareda_conanfile,
            "shareda/shareda.h": shareda_h,
            "shareda/shareda.c": shareda_c,
            "conanfile.py": _app_conanfile("shareda/1.0"),
            "build.zig": _BUILD_ZIG,
            "main.c": _main_c("shared_a_value")})
    c.run("create sharedb")
    c.run("create shareda")
    c.run("build .")
    assert "shared_a_value=11" in c.out


@pytest.mark.slow
@pytest.mark.tool("cmake")
@pytest.mark.tool("zig")
def test_zigdeps_shared_chain_cmake_deps():
    """ Same graph as test_zigdeps_shared_chain, but both shared libraries are built with
    CMake+the system compiler - only the final consumer uses Zig """
    c = TestClient()
    sharedb_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout

        class SharedB(ConanFile):
            name = "sharedb"
            version = "1.0"
            package_type = "shared-library"
            settings = "os", "compiler", "build_type", "arch"
            exports_sources = "CMakeLists.txt", "sharedb.c", "sharedb.h"
            generators = "CMakeToolchain"

            def layout(self):
                cmake_layout(self)

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.libs = ["sharedb"]
        """)
    sharedb_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(sharedb C)
        add_library(sharedb SHARED sharedb.c)
        set_target_properties(sharedb PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
        install(TARGETS sharedb
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES sharedb.h DESTINATION include)
        """)
    shareda_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout

        class SharedA(ConanFile):
            name = "shareda"
            version = "1.0"
            package_type = "shared-library"
            settings = "os", "compiler", "build_type", "arch"
            requires = "sharedb/1.0"
            exports_sources = "CMakeLists.txt", "shareda.c", "shareda.h"

            def layout(self):
                cmake_layout(self)

            def generate(self):
                CMakeDeps(self).generate()
                CMakeToolchain(self).generate()

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.libs = ["shareda"]
        """)
    shareda_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(shareda C)
        find_package(sharedb REQUIRED CONFIG)
        add_library(shareda SHARED shareda.c)
        set_target_properties(shareda PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
        target_link_libraries(shareda PUBLIC sharedb::sharedb)
        install(TARGETS shareda
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES shareda.h DESTINATION include)
        """)

    sharedb_h = "int shared_b_value(void);\n"
    sharedb_c = "int shared_b_value(void) { return 10; }\n"
    shareda_h = "int shared_a_value(void);\n"
    shareda_c = textwrap.dedent("""
        #include "sharedb.h"
        int shared_a_value(void) { return shared_b_value() + 1; }
        """)

    c.save({"sharedb/conanfile.py": sharedb_conanfile,
            "sharedb/CMakeLists.txt": sharedb_cmakelists,
            "sharedb/sharedb.h": sharedb_h,
            "sharedb/sharedb.c": sharedb_c,
            "shareda/conanfile.py": shareda_conanfile,
            "shareda/CMakeLists.txt": shareda_cmakelists,
            "shareda/shareda.h": shareda_h,
            "shareda/shareda.c": shareda_c,
            "conanfile.py": _app_conanfile("shareda/1.0"),
            "build.zig": _BUILD_ZIG_MATCHING_CONAN_ABI,
            "main.c": _main_c("shared_a_value")})
    c.run("create sharedb")
    c.run("create shareda")
    c.run("build .")
    assert "shared_a_value=11" in c.out


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_static_shared_static_chain():
    """ statictop (static) -> sharedmid (shared) -> staticleaf (static, private/invisible).
    sharedmid statically embeds staticleaf at its own build time, so staticleaf must NOT be
    relinked by (or even visible to) the final consumer - only statictop and sharedmid should
    show up in the generated ZigDeps map """
    c = TestClient()
    ext = _shared_ext()
    staticleaf_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class StaticLeaf(ConanFile):
            name = "staticleaf"
            version = "1.0"
            package_type = "static-library"
            exports_sources = "staticleaf.c", "staticleaf.h"

            def build(self):
                self.run("zig cc -c staticleaf.c -o staticleaf.o")
                self.run("zig ar rcs libstaticleaf.a staticleaf.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["staticleaf"]
        """)
    sharedmid_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class SharedMid(ConanFile):
            name = "sharedmid"
            version = "1.0"
            package_type = "shared-library"
            exports_sources = "sharedmid.c", "sharedmid.h"

            def requirements(self):
                # Private: fully embedded, must not propagate to further consumers
                self.requires("staticleaf/1.0", visible=False)

            def build(self):
                dep = self.dependencies["staticleaf"].cpp_info
                self.run('zig cc -c -Dsharedmid_EXPORTS sharedmid.c -I"'
                         + dep.includedirs[0] + '" -o sharedmid.o')
                self.run('zig cc -shared -fPIC %s -o libsharedmid%s sharedmid.o -L"'
                         + dep.libdirs[0] + '" -lstaticleaf')

            def package(self):
                copy(self, "*.dll", self.build_folder, os.path.join(self.package_folder, "bin"))
                copy(self, "*.so*", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.dylib", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["sharedmid"]
        """) % (_shared_link_flags("sharedmid"), ext)
    statictop_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class StaticTop(ConanFile):
            name = "statictop"
            version = "1.0"
            package_type = "static-library"
            requires = "sharedmid/1.0"
            exports_sources = "statictop.c", "statictop.h"

            def build(self):
                dep = self.dependencies["sharedmid"].cpp_info
                self.run('zig cc -c statictop.c -I"' + dep.includedirs[0] + '" -o statictop.o')
                self.run("zig ar rcs libstatictop.a statictop.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["statictop"]
        """)

    staticleaf_h = "int static_leaf_value(void);\n"
    staticleaf_c = "int static_leaf_value(void) { return 100; }\n"
    sharedmid_h = _export_header("sharedmid", "shared_mid_value")
    sharedmid_c = textwrap.dedent("""
        #include "sharedmid.h"
        #include "staticleaf.h"
        int shared_mid_value(void) { return static_leaf_value() + 1; }
        """)
    statictop_h = "int static_top_value(void);\n"
    statictop_c = textwrap.dedent("""
        #include "sharedmid.h"
        int static_top_value(void) { return shared_mid_value() + 1; }
        """)

    c.save({"staticleaf/conanfile.py": staticleaf_conanfile,
            "staticleaf/staticleaf.h": staticleaf_h,
            "staticleaf/staticleaf.c": staticleaf_c,
            "sharedmid/conanfile.py": sharedmid_conanfile,
            "sharedmid/sharedmid.h": sharedmid_h,
            "sharedmid/sharedmid.c": sharedmid_c,
            "statictop/conanfile.py": statictop_conanfile,
            "statictop/statictop.h": statictop_h,
            "statictop/statictop.c": statictop_c,
            "conanfile.py": _app_conanfile("statictop/1.0"),
            "build.zig": _BUILD_ZIG,
            "main.c": _main_c("static_top_value")})
    c.run("create staticleaf")
    c.run("create sharedmid")
    c.run("create statictop")
    c.run("build .")
    assert "static_top_value=102" in c.out

    deps_content = c.load("conan_zig_deps/conan_deps.zig")
    assert '"statictop::statictop"' in deps_content
    assert '"sharedmid::sharedmid"' in deps_content
    assert "staticleaf" not in deps_content  # private require, invisible to the consumer


@pytest.mark.slow
@pytest.mark.tool("cmake")
@pytest.mark.tool("zig")
def test_zigdeps_static_shared_static_chain_cmake_deps():
    """ Same graph as test_zigdeps_static_shared_static_chain, but all 3 dependencies are
    built with CMake+the system compiler - only the final consumer uses Zig """
    c = TestClient()
    staticleaf_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout

        class StaticLeaf(ConanFile):
            name = "staticleaf"
            version = "1.0"
            package_type = "static-library"
            settings = "os", "compiler", "build_type", "arch"
            exports_sources = "CMakeLists.txt", "staticleaf.c", "staticleaf.h"
            generators = "CMakeToolchain"

            def layout(self):
                cmake_layout(self)

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.libs = ["staticleaf"]
        """)
    staticleaf_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(staticleaf C)
        add_library(staticleaf STATIC staticleaf.c)
        install(TARGETS staticleaf
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES staticleaf.h DESTINATION include)
        """)
    sharedmid_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout

        class SharedMid(ConanFile):
            name = "sharedmid"
            version = "1.0"
            package_type = "shared-library"
            settings = "os", "compiler", "build_type", "arch"
            exports_sources = "CMakeLists.txt", "sharedmid.c", "sharedmid.h"

            def requirements(self):
                # Private: fully embedded, must not propagate to further consumers
                self.requires("staticleaf/1.0", visible=False)

            def layout(self):
                cmake_layout(self)

            def generate(self):
                CMakeDeps(self).generate()
                CMakeToolchain(self).generate()

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.libs = ["sharedmid"]
        """)
    sharedmid_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(sharedmid C)
        find_package(staticleaf REQUIRED CONFIG)
        add_library(sharedmid SHARED sharedmid.c)
        set_target_properties(sharedmid PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
        target_link_libraries(sharedmid PRIVATE staticleaf::staticleaf)
        install(TARGETS sharedmid
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES sharedmid.h DESTINATION include)
        """)
    statictop_conanfile = textwrap.dedent("""
        from conan import ConanFile
        from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout

        class StaticTop(ConanFile):
            name = "statictop"
            version = "1.0"
            package_type = "static-library"
            settings = "os", "compiler", "build_type", "arch"
            requires = "sharedmid/1.0"
            exports_sources = "CMakeLists.txt", "statictop.c", "statictop.h"

            def layout(self):
                cmake_layout(self)

            def generate(self):
                CMakeDeps(self).generate()
                CMakeToolchain(self).generate()

            def build(self):
                cmake = CMake(self)
                cmake.configure()
                cmake.build()

            def package(self):
                cmake = CMake(self)
                cmake.install()

            def package_info(self):
                self.cpp_info.libs = ["statictop"]
        """)
    statictop_cmakelists = textwrap.dedent("""
        cmake_minimum_required(VERSION 3.15)
        project(statictop C)
        find_package(sharedmid REQUIRED CONFIG)
        add_library(statictop STATIC statictop.c)
        target_link_libraries(statictop PUBLIC sharedmid::sharedmid)
        install(TARGETS statictop
                ARCHIVE DESTINATION lib
                LIBRARY DESTINATION lib
                RUNTIME DESTINATION bin)
        install(FILES statictop.h DESTINATION include)
        """)

    staticleaf_h = "int static_leaf_value(void);\n"
    staticleaf_c = "int static_leaf_value(void) { return 100; }\n"
    sharedmid_h = "int shared_mid_value(void);\n"
    sharedmid_c = textwrap.dedent("""
        #include "staticleaf.h"
        int shared_mid_value(void) { return static_leaf_value() + 1; }
        """)
    statictop_h = "int static_top_value(void);\n"
    statictop_c = textwrap.dedent("""
        #include "sharedmid.h"
        int static_top_value(void) { return shared_mid_value() + 1; }
        """)

    c.save({"staticleaf/conanfile.py": staticleaf_conanfile,
            "staticleaf/CMakeLists.txt": staticleaf_cmakelists,
            "staticleaf/staticleaf.h": staticleaf_h,
            "staticleaf/staticleaf.c": staticleaf_c,
            "sharedmid/conanfile.py": sharedmid_conanfile,
            "sharedmid/CMakeLists.txt": sharedmid_cmakelists,
            "sharedmid/sharedmid.h": sharedmid_h,
            "sharedmid/sharedmid.c": sharedmid_c,
            "statictop/conanfile.py": statictop_conanfile,
            "statictop/CMakeLists.txt": statictop_cmakelists,
            "statictop/statictop.h": statictop_h,
            "statictop/statictop.c": statictop_c,
            "conanfile.py": _app_conanfile("statictop/1.0"),
            "build.zig": _BUILD_ZIG_MATCHING_CONAN_ABI,
            "main.c": _main_c("static_top_value")})
    c.run("create staticleaf")
    c.run("create sharedmid")
    c.run("create statictop")
    c.run("build .")
    assert "static_top_value=102" in c.out

    deps_content = c.load("conan_zig_deps/conan_deps.zig")
    assert '"statictop::statictop"' in deps_content
    assert '"sharedmid::sharedmid"' in deps_content
    assert "staticleaf" not in deps_content  # private require, invisible to the consumer


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_link_single_component():
    """ ``linkDependency()`` can target one specific component directly, instead of using
    ``linkDependencies()`` (which links every direct dependency of the consumer wholesale) -
    and that component's own transitive dependency must still be pulled in correctly, even
    though it isn't the package's root target """
    c = TestClient()
    extdep_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class ExtDep(ConanFile):
            name = "extdep"
            version = "1.0"
            package_type = "static-library"
            exports_sources = "extdep.c", "extdep.h"

            def build(self):
                self.run("zig cc -c extdep.c -o extdep.o")
                self.run("zig ar rcs libextdep.a extdep.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["extdep"]
        """)
    multicomp_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class MultiComp(ConanFile):
            name = "multicomp"
            version = "1.0"
            package_type = "static-library"
            requires = "extdep/1.0"
            exports_sources = "used.c", "used.h", "other.c", "other.h"

            def build(self):
                dep = self.dependencies["extdep"].cpp_info
                self.run('zig cc -c used.c -I"' + dep.includedirs[0] + '" -o used.o')
                self.run("zig cc -c other.c -o other.o")
                self.run("zig ar rcs libused.a used.o")
                self.run("zig ar rcs libother.a other.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.components["used"].libs = ["used"]
                self.cpp_info.components["used"].requires = ["extdep::extdep"]
                self.cpp_info.components["other"].libs = ["other"]
        """)

    extdep_h = "int extdep_value(void);\n"
    extdep_c = "int extdep_value(void) { return 5; }\n"
    used_h = "int used_value(void);\n"
    used_c = textwrap.dedent("""
        #include "extdep.h"
        int used_value(void) { return extdep_value() + 1; }
        """)
    other_h = "int other_value(void);\n"
    other_c = "int other_value(void) { return 999; }\n"

    c.save({"extdep/conanfile.py": extdep_conanfile,
            "extdep/extdep.h": extdep_h,
            "extdep/extdep.c": extdep_c,
            "multicomp/conanfile.py": multicomp_conanfile,
            "multicomp/used.h": used_h,
            "multicomp/used.c": used_c,
            "multicomp/other.h": other_h,
            "multicomp/other.c": other_c,
            "conanfile.py": _app_conanfile("multicomp/1.0"),
            "build.zig": _build_zig_single_target("multicomp::used"),
            "main.c": _main_c("used_value")})
    c.run("create extdep")
    c.run("create multicomp")
    c.run("build .")
    assert "used_value=6" in c.out


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_cyclic_requires_does_not_hang():
    """ Regression test: cpp_info component requires can form a cycle (Conan doesn't validate
    against this, unlike the package dependency graph itself) - the generated
    linkDependency() must not recurse forever when that happens """
    c = TestClient()
    pkg_conanfile = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            name = "pkg"
            version = "1.0"

            def package_info(self):
                self.cpp_info.components["a"].includedirs = ["include/a"]
                self.cpp_info.components["a"].requires = ["b"]
                self.cpp_info.components["b"].includedirs = ["include/b"]
                self.cpp_info.components["b"].requires = ["a"]
        """)
    app_conanfile = textwrap.dedent("""
        from conan import ConanFile

        class App(ConanFile):
            requires = "pkg/1.0"
            generators = "ZigDeps"

            def build(self):
                self.run("zig build")
        """)
    build_zig = textwrap.dedent("""
        const std = @import("std");
        const conan_setup = @import("conan_zig_deps/conan_setup.zig");

        pub fn build(b: *std.Build) void {
            const target = b.standardTargetOptions(.{});
            const optimize = b.standardOptimizeOption(.{});
            const mod = b.createModule(.{ .target = target, .optimize = optimize });
            mod.addCSourceFile(.{ .file = b.path("main.c"), .flags = &.{} });
            mod.link_libc = true;
            const exe = b.addExecutable(.{ .name = "app", .root_module = mod });
            conan_setup.linkDependency(mod, "pkg::a");
            b.installArtifact(exe);
        }
        """)
    main_c = "int main(void) { return 0; }\n"

    c.save({"pkg/conanfile.py": pkg_conanfile,
            "conanfile.py": app_conanfile,
            "build.zig": build_zig,
            "main.c": main_c})
    c.run("create pkg")
    c.run("build .")


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_cpp_dependency():
    """ A C++ dependency must get the C++ runtime linked into the consumer. Without it the
    link fails with undefined std:: symbols - which every other functional test here misses,
    because they are all C-only """
    c = TestClient()
    cpplib_conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class CppLib(ConanFile):
            name = "cpplib"
            version = "1.0"
            package_type = "static-library"
            languages = "C++"
            exports_sources = "cpplib.cpp", "cpplib.h"

            def build(self):
                self.run("zig c++ -c cpplib.cpp -o cpplib.o")
                self.run("zig ar rcs libcpplib.a cpplib.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["cpplib"]
        """)
    # Uses std::string internally, so the C++ runtime is genuinely required at link time
    cpplib_h = 'extern "C" int cpp_value(void);\n'
    cpplib_cpp = textwrap.dedent("""
        #include "cpplib.h"
        #include <string>
        extern "C" int cpp_value(void) {
            std::string s = "1234";
            return static_cast<int>(s.size()) + 38;
        }
        """)

    c.save({"cpplib/conanfile.py": cpplib_conanfile,
            "cpplib/cpplib.h": cpplib_h,
            "cpplib/cpplib.cpp": cpplib_cpp,
            "conanfile.py": _app_conanfile("cpplib/1.0"),
            "build.zig": _BUILD_ZIG,
            "main.c": _main_c("cpp_value")})
    c.run("create cpplib")
    c.run("build .")
    assert "cpp_value=42" in c.out

    deps = c.load("conan_zig_deps/conan_deps.zig")
    assert ".link_cpp = true" in deps


@pytest.mark.slow
@pytest.mark.tool("zig")
def test_zigdeps_cpp_runtime_can_be_opted_out():
    """ link_libc/link_libcpp are ?bool in Zig, where null means "not decided", so ZigDeps
    only fills them in when the consumer has not. Setting link_libcpp explicitly therefore
    wins regardless of whether it comes before or after linkDependencies().

    Checked by building for real and looking at what Zig was actually told to link, rather
    than at the text of the generated file. """
    c = TestClient()
    # A C package: with `languages` unset it is assumed to be C++, so the C++ runtime is
    # requested for it - which is exactly what the consumer may want to undo.
    pkg = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import copy

        class Pkg(ConanFile):
            name = "cpkg"
            version = "1.0"
            package_type = "static-library"
            exports_sources = "val.c", "val.h"

            def build(self):
                self.run("zig cc -c val.c -o val.o")
                self.run("zig ar rcs libval.a val.o")

            def package(self):
                copy(self, "*.a", self.build_folder, os.path.join(self.package_folder, "lib"))
                copy(self, "*.h", self.build_folder, os.path.join(self.package_folder, "include"))

            def package_info(self):
                self.cpp_info.libs = ["val"]
        """)
    build_zig = textwrap.dedent("""
        const std = @import("std");
        const conan = @import("conan_zig_deps/conan_setup.zig");

        pub fn build(b: *std.Build) void {
            const mod = b.createModule(.{
                .root_source_file = b.path("main.zig"),
                .target = b.standardTargetOptions(.{}),
                .optimize = b.standardOptimizeOption(.{}),
            });
            %s
            const exe = b.addExecutable(.{ .name = "app", .root_module = mod });
            b.installArtifact(exe);
        }
        """)
    main_zig = textwrap.dedent("""
        const std = @import("std");
        const c = @cImport({ @cInclude("val.h"); });
        pub fn main() void { std.debug.print("{d}\\n", .{c.val()}); }
        """)
    app = textwrap.dedent("""
        from conan import ConanFile

        class App(ConanFile):
            settings = "os", "compiler", "build_type", "arch"
            requires = "cpkg/1.0"
            generators = "ZigDeps"

            def build(self):
                self.run("zig build --verbose", env="conanrun")
        """)

    c.save({"cpkg/conanfile.py": pkg,
            "cpkg/val.h": "int val(void);\n",
            "cpkg/val.c": "int val(void) { return 7; }\n",
            "conanfile.py": app,
            "main.zig": main_zig})
    c.run("create cpkg")

    def linked_libcpp(link_block):
        c.save({"build.zig": build_zig % link_block})
        c.run("build .")
        # --verbose prints the compile command; look at what Zig was actually asked to link
        return any(" -lc++" in line for line in c.out.splitlines())

    assert linked_libcpp("conan.linkDependencies(mod);") is True
    assert linked_libcpp("conan.linkDependencies(mod);\n            "
                         "mod.link_libcpp = false;") is False
    # …and opting out first must not be overwritten by the generator
    assert linked_libcpp("mod.link_libcpp = false;\n            "
                         "conan.linkDependencies(mod);") is False
