name: OSX Tests

on:
  push:
    branches:
      - develop2
      - release/*
      - ci/gh-action-osx
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    strategy:
      fail-fast: true
      matrix:
        test-type: [functional]
        python-version: ['3.9']

    runs-on: macos-14

    name: Conan ${{ matrix.test-type }} (${{ matrix.python-version }})

    steps:

      - name: Install default Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
          sudo xcode-select --install || true
          sudo xcodebuild -license accept
          sudo xcodebuild -runFirstLaunch
          xcodebuild -version
          xcrun --show-sdk-path
          xcrun --find clang++
          xcrun -find c++
          xcrun -find cc

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python requirements
        run: |
          pip install --upgrade pip
          pip install -r conans/requirements.txt
          pip install -r conans/requirements_server.txt
          pip install -r conans/requirements_dev.txt
          pip install meson

      - name: Install CMake versions
        run: |
          set -e
          for version in 3.15.7 3.16.9 3.17.5; do
            wget -q --no-check-certificate https://cmake.org/files/v${version%.*}/cmake-${version}-Darwin-x86_64.tar.gz
            tar -xzf cmake-${version}-Darwin-x86_64.tar.gz \
              --exclude=CMake.app/Contents/bin/cmake-gui \
              --exclude=CMake.app/Contents/doc/cmake \
              --exclude=CMake.app/Contents/share/cmake-${version%.*}/Help \
              --exclude=CMake.app/Contents/share/vim
            mkdir -p ${HOME}/Applications/CMake/${version}
            cp -fR cmake-${version}-Darwin-x86_64/CMake.app/Contents/* ${HOME}/Applications/CMake/${version}
            ${HOME}/Applications/CMake/${version}/bin/cmake --version
            rm -rf cmake-${version}-Darwin-x86_64
            rm cmake-${version}-Darwin-x86_64.tar.gz
          done
          for version in 3.19.7 3.23.1; do
            wget -q --no-check-certificate https://cmake.org/files/v${version%.*}/cmake-${version}-macos-universal.tar.gz
            tar -xzf cmake-${version}-macos-universal.tar.gz \
              --exclude=CMake.app/Contents/bin/cmake-gui \
              --exclude=CMake.app/Contents/doc/cmake \
              --exclude=CMake.app/Contents/share/cmake-${version%.*}/Help \
              --exclude=CMake.app/Contents/share/vim
            mkdir -p ${HOME}/Applications/CMake/${version}
            cp -fR cmake-${version}-macos-universal/CMake.app/Contents/* ${HOME}/Applications/CMake/${version}
            ${HOME}/Applications/CMake/${version}/bin/cmake --version
            rm -rf cmake-${version}-macos-universal
            rm cmake-${version}-macos-universal.tar.gz
          done

          brew uninstall cmake || true
          # the conftest.py defines CMake 3.15 as the default for testing
          export PATH="${HOME}/Applications/CMake/3.15.7/bin:$PATH"
          echo "The default CMake version for testing is:"
          cmake --version

      - name: Install Bazel versions
        run: |
          set -e
          for version in 6.3.2 7.1.2; do
            mkdir -p ${HOME}/Applications/bazel/${version}
            wget -q -O ${HOME}/Applications/bazel/${version}/bazel https://github.com/bazelbuild/bazel/releases/download/${version}/bazel-${version}-darwin-arm64
            chmod +x ${HOME}/Applications/bazel/${version}/bazel
          done

      - name: Install homebrew dependencies
        run: |
          brew install xcodegen make libtool xz zlib autoconf automake ninja

      - name: Run Test - ${{ matrix.test-type }}
        shell: bash
        env:
          CC: $(xcrun --find cc)
          CXX: $(xcrun --find c++)
        run: |
          if [ "${{ matrix.test-type }}" == "unittests" ]; then
            pytest test/unittests --durations=20
          elif [ "${{ matrix.test-type }}" == "integration" ]; then
            pytest test/integration --durations=20
          elif [ "${{ matrix.test-type }}" == "functional" ]; then
            pytest test/functional --durations=20
          fi
