name: Build Conan WoA Installer

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string

jobs:
  build-conan-installer:
    runs-on: windows-11-arm
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}
    steps:
      - name: Checkout Conan source
        uses: actions/checkout@v4
        with:
          repository: conan-io/conan
          ref: develop2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Install Conan (editable)
        run: |
          pip install -e .

      - name: Build Conan standalone installer
        run: |
          python pyinstaller.py

      - name: Upload Conan executable
        uses: actions/upload-artifact@v4
        with:
          name: conan-${{ matrix.python-version }}-win-arm64
          path: pyinstaller/dist/conan/